// <auto-generated />
using System;
using Miaudote.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Miaudote.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820143117_AdicionaAnimaisDemonstrativos")]
    partial class AdicionaAnimaisDemonstrativos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Miaudote.Web.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<bool>("Castrado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("castrado");

                    b.Property<int>("CidadeId")
                        .HasColumnType("int")
                        .HasColumnName("cidade_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)")
                        .HasColumnName("descricao");

                    b.Property<int>("EspecieId")
                        .HasColumnType("int")
                        .HasColumnName("especie_id");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("genero");

                    b.Property<int>("IdadeAproximadaMeses")
                        .HasColumnType("int")
                        .HasColumnName("idade_aproximada_meses");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeArquivoImagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_arquivo_imagem");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("porte");

                    b.Property<string>("Raca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("raca");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<bool>("Vacinado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("vacinado");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("EspecieId");

                    b.HasIndex("Status");

                    b.ToTable("animais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Castrado = true,
                            CidadeId = 2,
                            DataCadastro = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Max é um cão carinhoso, brincalhão e sociável. Procura uma família responsável e preparada para oferecer atenção, cuidados e um lar seguro.",
                            EspecieId = 1,
                            Genero = "Macho",
                            IdadeAproximadaMeses = 36,
                            Nome = "Max",
                            NomeArquivoImagem = "cachorro.jpg",
                            Porte = "Grande",
                            Raca = "Golden Retriever",
                            Status = "Disponivel",
                            Vacinado = true
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Castrado = true,
                            CidadeId = 4,
                            DataCadastro = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Luna é uma gata calma, carinhosa e independente. Procura um lar responsável, seguro e preparado para respeitar o seu período de adaptação.",
                            EspecieId = 2,
                            Genero = "Femea",
                            IdadeAproximadaMeses = 24,
                            Nome = "Luna",
                            NomeArquivoImagem = "luna.jpg",
                            Porte = "Pequeno",
                            Raca = "Gato sem raça definida",
                            Status = "Disponivel",
                            Vacinado = true
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Castrado = false,
                            CidadeId = 5,
                            DataCadastro = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Bob é um cão energético, curioso e sociável. Precisa de uma família que possa oferecer passeios, atividades e os cuidados necessários.",
                            EspecieId = 1,
                            Genero = "Macho",
                            IdadeAproximadaMeses = 48,
                            Nome = "Bob",
                            NomeArquivoImagem = "bob.jpg",
                            Porte = "Medio",
                            Raca = "Beagle",
                            Status = "Disponivel",
                            Vacinado = true
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Castrado = true,
                            CidadeId = 3,
                            DataCadastro = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mimi é uma gata jovem, calma, curiosa e carinhosa. Procura uma família responsável que ofereça proteção, acompanhamento e carinho.",
                            EspecieId = 2,
                            Genero = "Femea",
                            IdadeAproximadaMeses = 12,
                            Nome = "Mimi",
                            NomeArquivoImagem = "mimi.jpg",
                            Porte = "Pequeno",
                            Raca = "Siamês",
                            Status = "Disponivel",
                            Vacinado = true
                        });
                });

            modelBuilder.Entity("Miaudote.Web.Models.AnimalTemperamento", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<int>("TemperamentoId")
                        .HasColumnType("int")
                        .HasColumnName("temperamento_id");

                    b.HasKey("AnimalId", "TemperamentoId");

                    b.HasIndex("TemperamentoId");

                    b.ToTable("animais_temperamentos");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            TemperamentoId = 2
                        },
                        new
                        {
                            AnimalId = 1,
                            TemperamentoId = 3
                        },
                        new
                        {
                            AnimalId = 1,
                            TemperamentoId = 4
                        },
                        new
                        {
                            AnimalId = 2,
                            TemperamentoId = 1
                        },
                        new
                        {
                            AnimalId = 2,
                            TemperamentoId = 2
                        },
                        new
                        {
                            AnimalId = 2,
                            TemperamentoId = 6
                        },
                        new
                        {
                            AnimalId = 3,
                            TemperamentoId = 4
                        },
                        new
                        {
                            AnimalId = 3,
                            TemperamentoId = 5
                        },
                        new
                        {
                            AnimalId = 3,
                            TemperamentoId = 9
                        },
                        new
                        {
                            AnimalId = 4,
                            TemperamentoId = 1
                        },
                        new
                        {
                            AnimalId = 4,
                            TemperamentoId = 2
                        },
                        new
                        {
                            AnimalId = 4,
                            TemperamentoId = 9
                        });
                });

            modelBuilder.Entity("Miaudote.Web.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "Uf")
                        .IsUnique();

                    b.ToTable("cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Nome = "Barra Bonita",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Nome = "São Paulo",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            Nome = "Campinas",
                            Uf = "SP"
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            Nome = "Rio de Janeiro",
                            Uf = "RJ"
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            Nome = "Belo Horizonte",
                            Uf = "MG"
                        });
                });

            modelBuilder.Entity("Miaudote.Web.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("especies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Nome = "Cão"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Nome = "Gato"
                        });
                });

            modelBuilder.Entity("Miaudote.Web.Models.MensagemContato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("assunto");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_envio");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_resposta");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<bool>("Respondida")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("respondida");

                    b.HasKey("Id");

                    b.HasIndex("DataEnvio");

                    b.HasIndex("Respondida");

                    b.ToTable("mensagens_contato");
                });

            modelBuilder.Entity("Miaudote.Web.Models.SolicitacaoAdocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_solicitacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("endereco");

                    b.Property<string>("MotivoAdocao")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)")
                        .HasColumnName("motivo_adocao");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("ObservacaoAdministrativa")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)")
                        .HasColumnName("observacao_administrativa");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("DataSolicitacao");

                    b.HasIndex("Status");

                    b.ToTable("solicitacoes_adocao");
                });

            modelBuilder.Entity("Miaudote.Web.Models.Temperamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("temperamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Nome = "Calmo"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Nome = "Carinhoso"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Nome = "Brincalhão"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Nome = "Sociável"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Nome = "Energético"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Nome = "Independente"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Nome = "Obediente"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Nome = "Protetor"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Nome = "Curioso"
                        });
                });

            modelBuilder.Entity("Miaudote.Web.Models.Animal", b =>
                {
                    b.HasOne("Miaudote.Web.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Miaudote.Web.Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Miaudote.Web.Models.AnimalTemperamento", b =>
                {
                    b.HasOne("Miaudote.Web.Models.Animal", "Animal")
                        .WithMany("AnimaisTemperamentos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Miaudote.Web.Models.Temperamento", "Temperamento")
                        .WithMany("AnimaisTemperamentos")
                        .HasForeignKey("TemperamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Temperamento");
                });

            modelBuilder.Entity("Miaudote.Web.Models.SolicitacaoAdocao", b =>
                {
                    b.HasOne("Miaudote.Web.Models.Animal", "Animal")
                        .WithMany("SolicitacoesAdocao")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Miaudote.Web.Models.Animal", b =>
                {
                    b.Navigation("AnimaisTemperamentos");

                    b.Navigation("SolicitacoesAdocao");
                });

            modelBuilder.Entity("Miaudote.Web.Models.Temperamento", b =>
                {
                    b.Navigation("AnimaisTemperamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
